//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMMS_JCWEntities1 : DbContext
    {
        public EMMS_JCWEntities1()
            : base("name=EMMS_JCWEntities1")
        {
        }

        public EMMS_JCWEntities1(string connectStr):base(connectStr)
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PPT_PageNode> PPT_PageNode { get; set; }
        public DbSet<PPT_ProjectMetting> PPT_ProjectMetting { get; set; }
        public DbSet<PPT_Page> PPT_Page { get; set; }
    }
}
