//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPT_Page
    {
        public int ID { get; set; }
        public Nullable<int> PageIndex { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProjectMetting_ID { get; set; }
    }
}
