//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPT_PageNode
    {
        public int ID { get; set; }
        public Nullable<int> Page_ID { get; set; }
        public string Tag_Class { get; set; }
        public string Tag_ID { get; set; }
        public string Tag_Style { get; set; }
        public string Tag_OtherAttr { get; set; }
        public Nullable<int> PID { get; set; }
        public string Tag_Type { get; set; }
        public string Tag_Value { get; set; }
    }
}
